spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/exemplos
    username: postgres  
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8765

